import { useEffect, useState } from "react";
import { createAdminUser, deleteAdminUser, getAdminConductores, getAdminUsers, updateAdminUser } from "../services/api.js";
const empty = { nombre:"", username:"", correo:"", password:"", rol:"OPERADOR", activo:true, idConductor:"" };
export default function UsuariosAdminPage({ currentUser }) {
  const [users,setUsers]=useState([]), [drivers,setDrivers]=useState([]), [form,setForm]=useState(empty), [message,setMessage]=useState("");
  const load=async()=>{ try { const [u,d]=await Promise.all([getAdminUsers(),getAdminConductores({status:"ACTIVOS"})]); setUsers(u.data||[]); setDrivers(d.data||[]); } catch(e) { setMessage(e.message); } };
  useEffect(()=>{load();},[]);
  const submit=async(e)=>{e.preventDefault(); try { if(form.idUsuariosAdmin) await updateAdminUser(form.idUsuariosAdmin,form); else await createAdminUser(form); setForm(empty); setMessage("Cambios guardados."); load(); } catch(err){setMessage(err.message);} };
  return <section className="module-page"><header className="module-header"><div><span className="module-label">Administración</span><h1>Administrador de usuarios</h1><p>Gestiona jerarquías, accesos y la relación opcional de Operador con un conductor.</p></div></header>
    {message && <p className="module-message module-message-success">{message}</p>}
    <form className="driver-form" onSubmit={submit}><h2>{form.idUsuariosAdmin ? "Editar usuario" : "Nuevo usuario"}</h2><label>Nombre<input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Usuario<input required disabled={Boolean(form.idUsuariosAdmin)} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Correo<input type="email" value={form.correo||""} onChange={e=>setForm({...form,correo:e.target.value})}/></label>{!form.idUsuariosAdmin&&<label>Contraseña<input type="password" required minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}<label>Rol<select value={form.rol} onChange={e=>setForm({...form,rol:e.target.value})}>{["ADMINISTRADOR","SUPERVISOR","OPERADOR","CONSULTA"].map(x=><option key={x}>{x}</option>)}</select></label><label>Conductor vinculado<select value={form.idConductor||""} onChange={e=>setForm({...form,idConductor:e.target.value})}><option value="">No vinculado</option>{drivers.map(d=><option value={d.id_conductores} key={d.id_conductores}>{d.nombre}</option>)}</select></label><div className="form-actions"><button className="primary-button">Guardar usuario</button>{form.idUsuariosAdmin&&<button type="button" className="secondary-button" onClick={()=>setForm(empty)}>Cancelar</button>}</div></form>
    <section className="table-panel"><div className="table-wrapper"><table className="admin-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Conductor</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{users.map(u=><tr key={u.id_usuarios_admin}><td><strong>{u.nombre}</strong><br/><small>{u.username}</small></td><td>{u.rol}</td><td>{u.conductor||"—"}</td><td>{u.activo?"Activo":"Inactivo"}</td><td className="table-actions"><button className="edit-button" onClick={()=>setForm({idUsuariosAdmin:u.id_usuarios_admin,nombre:u.nombre,username:u.username,correo:u.correo||"",rol:u.rol,activo:u.activo,idConductor:u.id_conductores||""})}>Editar</button>{u.id_usuarios_admin!==currentUser.idUsuarioAdmin&&<button className="danger-button" onClick={async()=>{if(window.confirm("¿Eliminar este usuario?")){try{await deleteAdminUser(u.id_usuarios_admin);load();}catch(e){setMessage(e.message)}}}}>Eliminar</button>}</td></tr>)}</tbody></table></div></section></section>;
}
