import { useEffect, useState } from "react";
import { createAdminUser, deleteAdminUser, getAdminConductores, getAdminUsers, updateAdminUser } from "../services/api.js";
const empty={nombre:"",username:"",correo:"",password:"",rol:"OPERADOR",activo:true,idConductor:""};

export default function UsuariosAdminPage({ currentUser }) {
  const [users,setUsers]=useState([]),[drivers,setDrivers]=useState([]),[form,setForm]=useState(empty),[open,setOpen]=useState(false),[message,setMessage]=useState("");
  const load=async()=>{try{const [u,d]=await Promise.all([getAdminUsers(),getAdminConductores({status:"ACTIVOS"})]);setUsers(u.data||[]);setDrivers(d.data||[]);}catch(error){setMessage(error.message);}};
  useEffect(()=>{load();},[]);
  function create(){setForm(empty);setOpen(true);}
  function edit(user){setForm({idUsuariosAdmin:user.id_usuarios_admin,nombre:user.nombre,username:user.username,correo:user.correo||"",rol:user.rol,activo:user.activo,idConductor:user.id_conductores||""});setOpen(true);}
  async function submit(event){event.preventDefault();try{if(form.idUsuariosAdmin)await updateAdminUser(form.idUsuariosAdmin,form);else await createAdminUser(form);setOpen(false);setMessage("Cambios guardados.");load();}catch(error){setMessage(error.message);}}
  return <section className="module-page"><header className="module-header"><div><span className="module-label">Administración</span><h1>Administrador de usuarios</h1><p>Gestiona jerarquías, accesos y la relación opcional de Operador con un conductor.</p></div><button className="primary-button" onClick={create}>＋ Añadir usuario</button></header>
    {message&&<p className="module-message module-message-success">{message}</p>}
    <section className="table-panel"><div className="table-wrapper"><table className="admin-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Conductor</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{users.map(user=><tr key={user.id_usuarios_admin}><td><strong>{user.nombre}</strong><small>{user.username} · ID {user.id_usuarios_admin}</small></td><td>{user.rol}</td><td>{user.conductor||"—"}</td><td>{user.activo?"Activo":"Inactivo"}</td><td className="table-actions"><button className="edit-button" onClick={()=>edit(user)}>Editar</button>{user.id_usuarios_admin!==currentUser.idUsuarioAdmin&&<button className="danger-button" onClick={async()=>{if(window.confirm("¿Eliminar este usuario?")){try{await deleteAdminUser(user.id_usuarios_admin);load();}catch(error){setMessage(error.message)}}}}>Eliminar</button>}</td></tr>)}</tbody></table></div></section>
    {open&&<div className="modal-overlay" role="presentation"><section className="modal-card user-form-modal" role="dialog" aria-modal="true" aria-labelledby="user-form-title"><div className="form-panel-header"><div><h2 id="user-form-title">{form.idUsuariosAdmin?"Editar usuario":"Nuevo usuario"}</h2><p>Define el acceso y los datos de la cuenta administrativa.</p></div><button className="close-button" onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></div><form className="driver-form" onSubmit={submit}><label>Nombre<input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Usuario<input required disabled={Boolean(form.idUsuariosAdmin)} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Correo<input type="email" value={form.correo||""} onChange={e=>setForm({...form,correo:e.target.value})}/></label>{!form.idUsuariosAdmin&&<label>Contraseña<input type="password" required minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}<label>Rol<select value={form.rol} onChange={e=>setForm({...form,rol:e.target.value})}>{["ADMINISTRADOR","SUPERVISOR","OPERADOR","CONSULTA"].map(role=><option key={role}>{role}</option>)}</select></label><label>Conductor vinculado<select value={form.idConductor||""} onChange={e=>setForm({...form,idConductor:e.target.value})}><option value="">No vinculado</option>{drivers.map(driver=><option value={driver.id_conductores} key={driver.id_conductores}>{driver.nombre}</option>)}</select></label><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button">Guardar usuario</button></div></form></section></div>}
  </section>;
}
