import { useEffect, useRef, useState } from "react";
import { decidirSupervisorInspeccion, getSupervisorInspeccion, getSupervisorInspecciones, registrarSupervisor } from "../services/api.js";

function Signature({ onSave }) {
  const ref = useRef(null); const drawing = useRef(false); const [ink, setInk] = useState(false);
  function point(event) { const rect = ref.current.getBoundingClientRect(); return [event.clientX - rect.left, event.clientY - rect.top]; }
  function down(event) { const [x,y] = point(event); const c = ref.current.getContext("2d"); c.beginPath(); c.moveTo(x,y); c.lineWidth=2.5; c.lineCap="round"; drawing.current=true; setInk(true); }
  function move(event) { if (!drawing.current) return; const [x,y] = point(event); const c=ref.current.getContext("2d"); c.lineTo(x,y); c.stroke(); }
  return <section className="information-panel"><h3>Firma del supervisor</h3><canvas ref={ref} width="320" height="120" style={{width:"100%",border:"1px solid #466572", touchAction:"none"}} onPointerDown={down} onPointerMove={move} onPointerUp={()=>drawing.current=false} onPointerLeave={()=>drawing.current=false}/><button type="button" disabled={!ink} onClick={()=>onSave(ref.current.toDataURL("image/png"))}>Guardar firma</button></section>;
}

export default function SupervisorPortal({ access }) {
  const [form, setForm] = useState({ nombre:"", username:"", correo:"", telefono:"", password:"", confirmacionPassword:"" });
  const [items, setItems] = useState([]); const [detail, setDetail] = useState(null); const [message,setMessage]=useState(""); const [signature,setSignature]=useState(""); const [comment,setComment]=useState("");
  async function load() { try { setItems((await getSupervisorInspecciones()).data); } catch(error) { setMessage(error.message); } }
  useEffect(()=>{ if (access.confirmed) load(); }, [access.confirmed]);
  async function submitRegistration(event) { event.preventDefault(); try { const result=await registrarSupervisor(form); setMessage(result.message); } catch(error) { setMessage(error.message); } }
  async function open(id) { try { setDetail((await getSupervisorInspeccion(id)).data); setSignature(""); } catch(error) { setMessage(error.message); } }
  async function decide(aprobada) { try { const result=await decidirSupervisorInspeccion(detail.id_inspeccion,{aprobada,comentario:comment,firma:signature}); setMessage(result.message); setDetail(null); load(); } catch(error) { setMessage(error.message); } }
  if (!access.registered) return <main className="container"><h1>Registro de supervisor</h1><p>Elige un usuario de 3 a 100 caracteres: letras, números, punto, guion o guion bajo. Durante pruebas solo se acepta @itzamna.mx.</p><form onSubmit={submitRegistration}>{[["nombre","Nombre completo","text"],["username","Usuario","text"],["correo","Correo corporativo","email"],["telefono","Teléfono","tel"],["password","Contraseña (mínimo 10 caracteres)","password"],["confirmacionPassword","Confirmar contraseña","password"]].map(([key,label,type])=><label key={key}>{label}<input required type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button type="submit">Crear cuenta</button></form>{message&&<p className="message message-error">{message}</p>}</main>;
  if (!access.confirmed) return <main className="container"><h1>Confirma tu correo</h1><p>Te enviamos un enlace de bienvenida. Ábrelo y vuelve a entrar desde Telegram para activar las aprobaciones.</p>{message&&<p>{message}</p>}</main>;
  return <main className="container"><h1>Inspecciones pendientes</h1>{message&&<p className="message message-success">{message}</p>}{!detail ? <section>{items.length ? items.map(item=><button type="button" key={item.id_inspeccion} className="result-card" onClick={()=>open(item.id_inspeccion)}><strong>{item.folio}</strong><br/>{item.conductor} · {item.vehiculo} ({item.numero_economico})</button>) : <p>No hay inspecciones pendientes.</p>}</section> : <section className="result-card"><button type="button" onClick={()=>setDetail(null)}>← Volver</button><h2>{detail.folio}</h2><p><strong>Conductor:</strong> {detail.conductor}</p><p><strong>Unidad:</strong> {detail.vehiculo} · {detail.numero_economico}</p><p><strong>Combustible:</strong> {detail.combustible}</p><p><strong>Observaciones:</strong> {detail.observaciones_conductor||"Sin observaciones"}</p><h3>Checklist</h3>{Object.entries(detail.checklist||{}).map(([name,state])=><p key={name}>{state} — {name}</p>)}<label>Comentario<textarea value={comment} onChange={e=>setComment(e.target.value)}/></label>{signature ? <p>Firma guardada.</p> : <Signature onSave={setSignature}/>}<button type="button" disabled={!signature} onClick={()=>decide(false)}>Rechazar</button><button type="button" disabled={!signature} onClick={()=>decide(true)}>Aprobar y generar PDF</button></section>}</main>;
}
